### ISSUE TITLE
Can't find a LAT/LON which works on api

### ISSUE THREAD

**Issue by dawiduniec** [bieniu/ha-airly#6]
https://airapi.airly.eu/v2/measurements/point?indexType=AIRLY_CAQI&lat=54.32009&lng=18.63646 - does return proper value

sensor:
  - platform: airly
    name: 'Air Quality'
    api_key: '---------------------'
    latitude: '54.32009'
    longitude: '18.63646'
    language: 'pl'

Sat Nov 23 2019 09:41:57 GMT+0100 (Central European Standard Time)
Can't retrieve data: no Airly sensors in this area

**Comment by bieniu** [comment]
I used your configuration and integration works as usual.
```
sensor:
  - platform: airly
    name: 'dawiduniec'
    api_key: 'redacted'
    latitude: '54.32009'
    longitude: '18.63646'
```
![image](https://user-images.githubusercontent.com/478555/69476337-13d4d100-0dd9-11ea-9381-e569d70748e4.png)
